### ISSUE TITLE
transIndel detects INDELs up to 50bp of size

### ISSUE THREAD

**Issue by kostasgalexiou** [cauyrd/transIndel#8]
Hi,

I have used transIndel to detect mid-sized INDELs (<1kbp) in a set of peach varieties but the software detects only INDELs of <50bp. Which is strange because, on other cases, transIndel is able to detect INDELs up to several tens of kilobases. Moreover, when I use a different software I do detect mid-sized INDELs that I confirm them by looking at IGV. Below are the commands that I used for running transIndel.

python ~/local/software/transIndel/transIndel_build_DNA.py -i $inbam -o transIndel/$out'.build'
python ~/local/software/transIndel/transIndel_call.py -i $out'.build' -o $out'.call' -l 1

Any suggestion will be greatly appreciated.

Regards,
Kostas

**Comment by cauyrd** [comment]
Do you use BWA-MEM align your reads? What is your read length. transIndel
may detect insertion < 50 bp if your read length is around 100bp, but for
deletion, it can detect them in any size if your read length >75bp. The
sequencing depth of your data may also affect the sensitivity. I recommend
to have > 20x coverage for reliable performance. If still have problem,
could you send a spliced bam file which takes the indel you validated in
IGV and I can further test the case.

**Comment by kostasgalexiou** [comment]
Hi,

I have used BWA-MEM for the alignment. Reads are 100nt long. I see that for insertion it may be difficult for transIndel to detect them but, as you mention, it shouldn't be a problem for the deletion.

I am sending you 2 bam files (links below; bam file and its index), where one of them contains a 838bp deletion, detected by another software. 

https://drive.google.com/file/d/1sX4zXdhEU7CjG_koTfHSdRfpXyCzG2AJ/view?usp=sharing
https://drive.google.com/file/d/1K0tMPakdTr1tw_ywdooMTLJX6FekeqJC/view?usp=sharing
https://drive.google.com/file/d/1u4SrSPp5yHSU4ElChQFxE6s5EYUz3lLt/view?usp=sharing
https://drive.google.com/file/d/1wLiNRzgqGSXJbKF4RcJ2urLtAD4k7P_P/view?usp=sharing


I am also attaching a snapshot from the IGV. Do you want me to send you the reference genome as well?

![snapshot](https://user-images.githubusercontent.com/54025256/79048487-a9082300-7c1d-11ea-81e2-bf2448aa1d04.png)

Thanks
Kostas

**Comment by cauyrd** [comment]
The reason why transIndel missed this case is that your aligned reads by
BWA-MEM did not generate alternative alignments for soft-lipped reads. Any
alternative alignment can be found by a SA tag in the BAM file and I didi
not find any reads take this SA tag. This cause transIndel unable to locate
the split reads for indels. Did you align your reads with some special
parameters of BWA-MEM?

**Comment by kostasgalexiou** [comment]
I see. I have my bam files filtered for SA and XA tags since these tags refer to supplementary alignmets. I thought that soft-clipped reads are detected by transIndel from the CIGAR value and, being soft-clipped, have the corresponding sequence available on the aligned read.

**Comment by kostasgalexiou** [comment]
You are correct! I have repeated the analysis, including SA tags, and obtained larger INDELs.

Thanks a lot.
